services:
  app:
    image: evgen1771/ai-post-generator:latest
    container_name: post-generator
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - ./drone-data:/app/drone-data
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    command: streamlit run 🏠_Главная.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false
