name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 103.125.216.112
        username: deploy
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2222
        script: |
          cd /var/www/apps/post-generator/ai-post-generator
          git pull origin main
          sudo docker compose down
          sudo docker compose up -d --build
          sudo docker system prune -f
